language: rust
cache: cargo

branches:
  except:
    - /^v[0-9]/

services:
  - postgresql

addons:
  postgresql: 10
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - postgresql-10-postgis-2.4

env:
  - DATABASE_URL=postgres://postgres@localhost/test

before_script:
  - psql -U postgres -c 'create database test'
  - psql -U postgres -d test -c 'create extension postgis'
  - psql -U postgres -d test -f fixtures/tilebbox.sql
  - psql -U postgres -d test -f fixtures/points.sql

script:
  - cargo test --verbose --all