language: rust
cache: cargo

dist: trusty
sudo: required

branches:
  except:
    - /^v[0-9]/

services:
  - postgresql

addons:
  postgresql: 9.6
  # apt:
  #   packages:
  #     - postgresql-9.6-postgis-2.4

env:
  - DATABASE_URL=postgres://postgres@localhost/test

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-9.6-postgis-2.4
  - psql -U postgres -c 'create database test'
  - psql -U postgres -d test -c 'create extension postgis'
  - psql -U postgres -d test -f fixtures/tilebbox.sql
  - psql -U postgres -d test -f fixtures/points.sql

script:
  - cargo test --verbose --all