[package]
name = "falcon"
version = "0.1.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]

[[bin]]
name = "falcon"
path = "src/main.rs"

[dependencies]
url = "1.6.0"
regex = "0.2.2"
fallible-iterator = "0.1.3"
iron = "0.5.1"
persistent = "0.3.0"
serde_json = "1.0.6"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
postgres = { version = "0.15.1", features = ["with-serde_json", "with-time", "with-uuid"] }
