[package]
name = "martin"
version = "0.1.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]

[[bin]]
name = "martin"
path = "src/main.rs"

[dependencies]
regex = "0.2.2"
iron = "0.6.0"
iron-test = "0.6.0"
rererouter = "0.1.1"
persistent = "0.4.0"
lazy_static = "0.2.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tilejson = "0.1.0"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
postgres = { version = "0.15.1", features = ["with-time", "with-uuid"] }