[package]
name = "martin"
version = "0.1.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]

[dependencies]
actix = { git = "https://github.com/actix/actix.git", branch = "master" }
actix-web = { git = "https://github.com/actix/actix-web.git", branch = "master" }
env_logger = "0.5.3"
futures = "0.1.18"
log = "0.4.1"
postgres = { version = "0.15", features = ["with-time", "with-uuid", "with-serde_json"] }
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"