[package]
name = "falcon"
version = "0.1.0"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]

[[bin]]
name = "falcon"
path = "src/main.rs"

[dependencies]
url = "1.6.0"
regex = "0.2.2"
iron = "0.6.0"
persistent = "0.4.0"
r2d2 = "0.7.4"
r2d2_postgres = "0.13.0"
postgres = { version = "0.15.1", features = ["with-time", "with-uuid"] }
