version: '3.7'

services:
#  front:
#    build:
#      context: .
#      dockerfile: front.Dockerfile
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - 3000:3000
#    environment:
#      - NODE_ENV=development
  data:
    build:
      context: .
      dockerfile: data.Dockerfile
    depends_on:
      - db
    volumes:
      - ./data:/data
  martin:
    image: urbica/martin
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/db
    depends_on:
      - db
  db:
    image: timescale/timescaledb-postgis
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/data
      - ./db:/var/lib/postgresql/data
      - ./scripts/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
