name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build -t docker.pkg.github.com/urbica/martin/martin:latest .
      - name: Push the image to the GitHub Package Registry
        run: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push docker.pkg.github.com/urbica/martin/martin:latest
        if: github.ref == 'refs/heads/master'
