name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Create changelog
        run: |
          cargo install clog-cli
          clog --from-latest-tag -i '' -o RELEASENOTES.md --setversion ${{ github.ref }}

      - name: Build assets
        run: |
          cd ./target/release
          zip martin-${{ matrix.os }}-${{ github.ref }}.zip martin
          shasum -a 256 martin-${{ matrix.os }}-${{ github.ref }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASENOTES.md
          files: martin-${{ matrix.os }}-${{ github.ref }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
