name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Create changelog
        run: |
          ls -las
          echo $TAG
          cargo install clog-cli
          clog --from-latest-tag -i '' -o RELEASENOTES.md --setversion $TAG
          cat RELEASENOTES.md
        env:
          TAG: $(git describe --tags --abbrev=0)

      - name: Build assets
        run: |
          ls -las
          cd ./target/release
          zip martin-${{ matrix.os }}-$TAG.zip martin
          shasum -a 256 martin-${{ matrix.os }}-$TAG.zip
        env:
          TAG: $(git describe --tags --abbrev=0)

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASENOTES.md
          files: martin-${{ matrix.os }}-$TAG.zip
        env:
          TAG: $(git describe --tags --abbrev=0)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
