name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Create changelog
        run: |
          ls -las
          cargo install clog-cli
          clog --from-latest-tag -i '' -o RELEASENOTES.md --setversion $(git describe --tags --abbrev=0)
          cat RELEASENOTES.md

      - name: Build assets
        run: |
          ls -las
          ls -las target
          ls -las target/release
          cd ./target/release
          export ARCHIVE=martin-${{ matrix.os }}-$(git describe --tags --abbrev=0).zip
          zip $ARCHIVE martin
          shasum -a 256 $ARCHIVE

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASENOTES.md
          files: martin-${{ matrix.os }}-$(git describe --tags --abbrev=0).zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
